title: GameDeploy manifest schema
description: A schema to validate a GameDeploy manifest.yaml
type: object
required:
  - name
  - description
  - etag
properties:
  name:
    type: string
    description: The name of manifest
  description:
    type: string
    description: The description of manifest
  etag:
    type: string
    description: Unique for single manifest ETag
